"""init: create all tables (user/rbac/knowledge/conversation/ai/ticket/tenant)

Revision ID: 0391ca308092
Revises: 
Create Date: 2026-09-09 13:14:09.210419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0391ca308092'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_config',
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='模型名称'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='供应商:openai/deepseek/qwen/anthropic'),
    sa.Column('api_url', sa.String(length=255), nullable=True, comment='API 地址'),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), nullable=True, comment='温度参数'),
    sa.Column('max_tokens', sa.Integer(), nullable=True, comment='最大 token 数'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('name', sa.String(length=100), nullable=False, comment='权限名称'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='权限编码'),
    sa.Column('api_path', sa.String(length=255), nullable=True, comment='API路径'),
    sa.Column('method', sa.String(length=10), nullable=True, comment='HTTP方法'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('prompt_template',
    sa.Column('name', sa.String(length=100), nullable=False, comment='模板名称'),
    sa.Column('scene', sa.String(length=50), nullable=True, comment='场景:customer_service/sales/complaint'),
    sa.Column('content', sa.Text(), nullable=False, comment='模板内容'),
    sa.Column('version', sa.String(length=20), nullable=True, comment='版本号'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='角色编码'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tenant',
    sa.Column('name', sa.String(length=100), nullable=False, comment='企业名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='企业编码'),
    sa.Column('contact_name', sa.String(length=50), nullable=True, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    comment='角色-权限关联表'
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录账号'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='加密密码'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态:1启用 0禁用'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='所属租户'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('conversation',
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='所属租户'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='发起用户'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='会话标题'),
    sa.Column('channel', sa.String(length=50), nullable=False, comment='渠道:web/wechat/app/email'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态:1进行中 0已结束'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_base',
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='所属租户'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='知识库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('embedding_model', sa.String(length=100), nullable=True, comment='嵌入模型'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    comment='用户-角色关联表'
    )
    op.create_table('document',
    sa.Column('kb_id', sa.BigInteger(), nullable=False, comment='所属知识库'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小(字节)'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='文件类型'),
    sa.Column('storage_path', sa.String(length=500), nullable=True, comment='存储路径'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态:0上传中 1解析中 2切块中 3向量化 4完成 5失败'),
    sa.Column('upload_user', sa.BigInteger(), nullable=True, comment='上传人'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_base.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_user'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('conversation_id', sa.BigInteger(), nullable=False, comment='所属会话'),
    sa.Column('sender_type', sa.String(length=20), nullable=False, comment='发送方类型:user/ai/human/system'),
    sa.Column('sender_id', sa.BigInteger(), nullable=True, comment='发送方ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('message_type', sa.String(length=20), nullable=True, comment='消息类型:text/image/file'),
    sa.Column('token_count', sa.Integer(), nullable=True, comment='token 数'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('conversation_id', sa.BigInteger(), nullable=True, comment='关联会话'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='提交用户'),
    sa.Column('assigned_user', sa.BigInteger(), nullable=True, comment='指派客服'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态:0待处理 1处理中 2已完成 3已关闭'),
    sa.Column('priority', sa.SmallInteger(), nullable=False, comment='优先级:1低 2中 3高'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.ForeignKeyConstraint(['assigned_user'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunk',
    sa.Column('document_id', sa.BigInteger(), nullable=False, comment='所属文档'),
    sa.Column('chunk_no', sa.Integer(), nullable=False, comment='块序号'),
    sa.Column('content', sa.Text(), nullable=False, comment='块内容'),
    sa.Column('token_count', sa.Integer(), nullable=True, comment='token 数'),
    sa.Column('embedding_status', sa.SmallInteger(), nullable=False, comment='向量化状态:0未向量化 1已向量化 2失败'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_message',
    sa.Column('ticket_id', sa.BigInteger(), nullable=False, comment='所属工单'),
    sa.Column('sender_id', sa.BigInteger(), nullable=True, comment='发送人ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vector_index',
    sa.Column('chunk_id', sa.BigInteger(), nullable=False, comment='所属切块'),
    sa.Column('vector_id', sa.String(length=100), nullable=False, comment='向量库中的ID'),
    sa.Column('platform', sa.String(length=50), nullable=False, comment='向量平台:milvus/pgvector/es'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vector_index')
    op.drop_table('ticket_message')
    op.drop_table('document_chunk')
    op.drop_table('ticket')
    op.drop_table('message')
    op.drop_table('document')
    op.drop_table('user_role')
    op.drop_table('knowledge_base')
    op.drop_table('conversation')
    op.drop_table('user')
    op.drop_table('role_permission')
    op.drop_table('tenant')
    op.drop_table('role')
    op.drop_table('prompt_template')
    op.drop_table('permission')
    op.drop_table('model_config')
    # ### end Alembic commands ###
